# db/seeds.rb

puts "Limpando a base de dados de itens..."
Item.destroy_all

puts "Criando itens..."

items_list = [
  { name: "Rusty Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Hardened Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Rusty surgical Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Surgical Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced surgical Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Hardened surgical Ripper", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Gauss pistol", category: "Weapons", rarity: "Rare" },
  { name: "Focused Gauss pistol", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Gauss pistol", category: "Weapons", rarity: "Rare" },
  { name: "Hardened Gauss pistol", category: "Weapons", rarity: "Rare" },
  { name: "Rusty tranq gun", category: "Weapons", rarity: "Rare" },
  { name: "Tranq gun", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced tranq gun", category: "Weapons", rarity: "Rare" },
  { name: "Hardened tranq gun", category: "Weapons", rarity: "Rare" },
  { name: "Rusty T60 pistol", category: "Weapons", rarity: "Rare" },
  { name: "T60 pistol", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced T60 pistol", category: "Weapons", rarity: "Rare" },
  { name: "Hardened T60 pistol", category: "Weapons", rarity: "Rare" },
  { name: "Armor piercing T60 pistol", category: "Weapons", rarity: "Rare" },
  { name: "BOS assault rifle", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced BOS assault rifle", category: "Weapons", rarity: "Rare" },
  { name: "Hardened BOS assault rifle", category: "Weapons", rarity: "Rare" },
  { name: "Armor piercing BOS assault rifle", category: "Weapons", rarity: "Rare" },
  { name: "Double-barrel combat shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Assaultron head", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Assaultron head", category: "Weapons", rarity: "Rare" },
  { name: "Hardened Assaultron head", category: "Weapons", rarity: "Rare" },
  { name: ".50 cal machine gun", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced .50 cal machine gun", category: "Weapons", rarity: "Rare" },
  { name: "Hardened .50 cal machine gun", category: "Weapons", rarity: "Rare" },
  { name: "Armor piercing .50 cal machine gun", category: "Weapons", rarity: "Rare" },
  { name: "Calibrated pipe rifle", category: "Weapons", rarity: "Rare" },
  { name: "Long pipe rifle", category: "Weapons", rarity: "Rare" },
  { name: "Fire hydrant bat", category: "Weapons", rarity: "Legendary" },
  { name: "Rusty power fist", category: "Weapons", rarity: "Legendary" },
  { name: "Power fist", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced power fist", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened power fist", category: "Weapons", rarity: "Legendary" },
  { name: "Ed's custom power fist", category: "Weapons", rarity: "Legendary" },
  { name: "Grognak's axe", category: "Weapons", rarity: "Legendary" },
  { name: "Wild Bill's Sidearm", category: "Weapons", rarity: "Legendary" },
  { name: "Infiltrator", category: "Weapons", rarity: "Legendary" },
  { name: "Red Rocket", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened Gauss rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Accelerated Gauss rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Magnetron 4000", category: "Weapons", rarity: "Legendary" },
  { name: "Henrietta", category: "Weapons", rarity: "Legendary" },
  { name: "Ol' Painless", category: "Weapons", rarity: "Legendary" },
  { name: "Mare's Leg", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened railway rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Railmaster", category: "Weapons", rarity: "Legendary" },
  { name: "Victory rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Charon's shotgun", category: "Weapons", rarity: "Legendary" },
  { name: "Mountain Momma", category: "Weapons", rarity: "Legendary" },
  { name: "Kneecapper", category: "Weapons", rarity: "Legendary" },
  { name: "Farmer's Daughter", category: "Weapons", rarity: "Legendary" },
  { name: "Ghoul revolver", category: "Weapons", rarity: "Legendary" },
  { name: "Alien blaster", category: "Weapons", rarity: "Legendary" },
  { name: "Destabilizer", category: "Weapons", rarity: "Legendary" },
  { name: "Smuggler's End", category: "Weapons", rarity: "Legendary" },
  { name: "MPXL Novasurge", category: "Weapons", rarity: "Legendary" },
  { name: "Alien disintegrator", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced alien disintegrator", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened alien disintegrator", category: "Weapons", rarity: "Legendary" },
  { name: "Tuned plasma rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Focused plasma rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Pulse rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced pulse rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened pulse rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced Fat Man", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened Fat Man", category: "Weapons", rarity: "Legendary" },
  { name: "Guided Fat Man", category: "Weapons", rarity: "Legendary" },
  { name: "Burnmaster", category: "Weapons", rarity: "Legendary" },
  { name: "Tuned Gatling laser", category: "Weapons", rarity: "Legendary" },
  { name: "Focused Gatling laser", category: "Weapons", rarity: "Legendary" },
  { name: "Amplified Gatling laser", category: "Weapons", rarity: "Legendary" },
  { name: "Minigun", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced minigun", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened minigun", category: "Weapons", rarity: "Legendary" },
  { name: "Lead Belcher", category: "Weapons", rarity: "Legendary" },
  { name: "Missile launcher", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced missile launcher", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened missile launcher", category: "Weapons", rarity: "Legendary" },
  { name: "Plasma caster", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced plasma caster", category: "Weapons", rarity: "Legendary" },
  { name: "Hardened plasma caster", category: "Weapons", rarity: "Legendary" },
  { name: "Scoped Institute pistol", category: "Weapons", rarity: "Legendary" },
  { name: "Scattered Institute pistol", category: "Weapons", rarity: "Legendary" },
  { name: "Long Institute rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Night-vision Institute rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Targeting Institute rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Virgil's rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Electrified Junk Jet", category: "Weapons", rarity: "Legendary" },
  { name: "Technician's Revenge", category: "Weapons", rarity: "Legendary" },
  { name: "Big Sister", category: "Weapons", rarity: "Legendary" },
  { name: "Agitated plasma thrower", category: "Weapons", rarity: "Legendary" },
  { name: "Tactical plasma thrower", category: "Weapons", rarity: "Legendary" },
  { name: "Boosted plasma thrower", category: "Weapons", rarity: "Legendary" },
  { name: "Overcharged plasma thrower", category: "Weapons", rarity: "Legendary" },
  { name: "Vault suit", category: "Outfits", rarity: "Common" },
  { name: "RobCo factory uniform", category: "Outfits", rarity: "Common" },
  { name: "Accountant outfit", category: "Outfits", rarity: "Common" },
  { name: "Agent provocateur", category: "Outfits", rarity: "Common" },
  { name: "Bespoke attire", category: "Outfits", rarity: "Common" },
  { name: "BOS casual", category: "Outfits", rarity: "Rare" },
  { name: "NCR Ranger outfit", category: "Outfits", rarity: "Rare" },
  { name: "RobCo R&D suit", category: "Outfits", rarity: "Rare" },
  { name: "Robot armor", category: "Outfits", rarity: "Rare" },
  { name: "Bowling shirt", category: "Outfits", rarity: "Rare" },
  { name: "Swing dress", category: "Outfits", rarity: "Rare" },
  { name: "Elf outfit", category: "Outfits", rarity: "Rare" },
  { name: "Enclave security outfit", category: "Outfits", rarity: "Rare" },
  { name: "Ghost costume", category: "Outfits", rarity: "Rare" },
  { name: "Pilgrim outfit", category: "Outfits", rarity: "Rare" },
  { name: "Santa suit", category: "Outfits", rarity: "Rare" },
  { name: "Skeleton costume", category: "Outfits", rarity: "Rare" },
  { name: "Vault 33 suit", category: "Outfits", rarity: "Rare" },
  { name: "Ma June jacket", category: "Outfits", rarity: "Rare" },
  { name: "Sleazy suit", category: "Outfits", rarity: "Rare" },
  { name: "Prewar cowboy costume", category: "Outfits", rarity: "Rare" },
  { name: "Wedding dress", category: "Outfits", rarity: "Rare" },
  { name: "Action wedding dress", category: "Outfits", rarity: "Rare" },
  { name: "Vault security outfit", category: "Outfits", rarity: "Rare" },
  { name: "Heavy vault suit", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy battle armor", category: "Outfits", rarity: "Legendary" },
  { name: "Expert jumpsuit", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy leather armor", category: "Outfits", rarity: "Legendary" },
  { name: "Commander fatigues", category: "Outfits", rarity: "Legendary" },
  { name: "Lucky nightwear", category: "Outfits", rarity: "Legendary" },
  { name: "Mutant hunter gear", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy metal armor", category: "Outfits", rarity: "Legendary" },
  { name: "Tattered longcoat", category: "Outfits", rarity: "Legendary" },
  { name: "Autumn's uniform", category: "Outfits", rarity: "Legendary" },
  { name: "Bittercup's outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Eulogy Jones' suit", category: "Outfits", rarity: "Legendary" },
  { name: "Incognito leisurewear", category: "Outfits", rarity: "Legendary" },
  { name: "Lucy's vault suit", category: "Outfits", rarity: "Legendary" },
  { name: "Moldaver's armor", category: "Outfits", rarity: "Legendary" },
  { name: "Nuka-Girl outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Overseer's office wear", category: "Outfits", rarity: "Legendary" },
  { name: "Piper's outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Preston's outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Rachel's outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Sarah Lyons' Brotherhood fatigues", category: "Outfits", rarity: "Legendary" },
  { name: "Silver Shroud costume", category: "Outfits", rarity: "Legendary" },
  { name: "Virgil's lab coat", category: "Outfits", rarity: "Legendary" },
  { name: "Wasteland wanderer", category: "Outfits", rarity: "Legendary" },
  { name: "Zeta alien outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Zeta alien spacesuit", category: "Outfits", rarity: "Legendary" },
  { name: "Tunnel Snake outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Mechanist Jumpsuit", category: "Outfits", rarity: "Common" },
  { name: "Polka Dot Sundres", category: "Outfits", rarity: "Common" },
  { name: "Pre-war Suburbanite", category: "Outfits", rarity: "Common" },
  { name: "Rural Schoolmarm", category: "Outfits", rarity: "Common" },
  { name: "Spring Casualwear", category: "Outfits", rarity: "Common" },
  { name: "Vailt Socialite", category: "Outfits", rarity: "Common" },
  { name: "Armored Vault Suit", category: "Outfits", rarity: "Common" },
  { name: "Battle Armor", category: "Outfits", rarity: "Common" },
  { name: "BoS Uniform", category: "Outfits", rarity: "Common" },
  { name: "Combat Armor", category: "Outfits", rarity: "Common" },
  { name: "Flight Suit", category: "Outfits", rarity: "Common" },
  { name: "Formal Wear", category: "Outfits", rarity: "Common" },
  { name: "Handyman Jumpsuit", category: "Outfits", rarity: "Common" },
  { name: "Iniate Robe", category: "Outfits", rarity: "Common" },
  { name: "Junior Officer Uniform", category: "Outfits", rarity: "Common" },
  { name: "Lab Coat", category: "Outfits", rarity: "Common" },
  { name: "Leather Armor", category: "Outfits", rarity: "Common" },
  { name: "Merc Gear", category: "Outfits", rarity: "Common" },
  { name: "Military Fatigues", category: "Outfits", rarity: "Common" },
  { name: "Nightwear", category: "Outfits", rarity: "Common" },
  { name: "Radiation Suit", category: "Outfits", rarity: "Common" },
  { name: "Raider Armor", category: "Outfits", rarity: "Common" },
  { name: "Treasure Gear", category: "Outfits", rarity: "Common" },
  { name: "Wasteland Gear", category: "Outfits", rarity: "Common" },
  { name: "Wasteland Medic", category: "Outfits", rarity: "Common" },
  { name: "Business Suit", category: "Outfits", rarity: "Common" },
  { name: "Country Girl", category: "Outfits", rarity: "Common" },
  { name: "Waitress Uniform", category: "Outfits", rarity: "Common" },
  { name: "Doo-wop Singer", category: "Outfits", rarity: "Common" },
  { name: "Drag Racer", category: "Outfits", rarity: "Common" },
  { name: "Post-War Casanova", category: "Outfits", rarity: "Common" },
  { name: "Soda Fountain Dress", category: "Outfits", rarity: "Common" },
  { name: "Advanced BoS Uniform", category: "Outfits", rarity: "Rare" },
  { name: "advanced Flight Suit", category: "Outfits", rarity: "Rare" },
  { name: "Advanced Institute Jumper", category: "Outfits", rarity: "Rare" },
  { name: "Advanced Jumpsuit", category: "Outfits", rarity: "Rare" },
  { name: "Advanced Lab Coat", category: "Outfits", rarity: "Rare" },
  { name: "Advanced Radiation Suit", category: "Outfits", rarity: "Rare" },
  { name: "Baseball Uniform", category: "Outfits", rarity: "Rare" },
  { name: "Bounty Hunter Gear", category: "Outfits", rarity: "Rare" },
  { name: "Clergy Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Comedian Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Engineer Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Fancy Formal Wear", category: "Outfits", rarity: "Rare" },
  { name: "Greaser Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Horror Fan Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Knight Armor", category: "Outfits", rarity: "Rare" },
  { name: "Librarian Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Lifeguard Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Mayor Ouitfit", category: "Outfits", rarity: "Rare" },
  { name: "Medieval Ruler Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Movie Fan outfit", category: "Outfits", rarity: "Rare" },
  { name: "Naughty Night Wear", category: "Outfits", rarity: "Rare" },
  { name: "Ninja Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Nobility Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Officer Fatigues", category: "Outfits", rarity: "Rare" },
  { name: "Officer Uniform", category: "Outfits", rarity: "Rare" },
  { name: "Professor Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Republic Robes", category: "Outfits", rarity: "Rare" },
  { name: "Sci-Fi Fan Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Scribe Robe", category: "Outfits", rarity: "Rare" },
  { name: "Soldier Uniform", category: "Outfits", rarity: "Rare" },
  { name: "Sports Fan outfit", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Battler Armor", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Combat Armor", category: "Outfits", rarity: "Rare" },
  { name: "Aturdy Leather Armor", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Merc Gear", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Metal Armor", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Raider Armor", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Vault Suit", category: "Outfits", rarity: "Rare" },
  { name: "Sturdy Wasteland Gear", category: "Outfits", rarity: "Rare" },
  { name: "Surgeon Outfit", category: "Outfits", rarity: "Rare" },
  { name: "Survivor Armor", category: "Outfits", rarity: "Rare" },
  { name: "Swimsuit", category: "Outfits", rarity: "Rare" },
  { name: "Wasteland Doctor", category: "Outfits", rarity: "Rare" },
  { name: "Wrestler outfit", category: "Outfits", rarity: "Rare" },
  { name: "Motorcycle Jacket", category: "Outfits", rarity: "Rare" },
  { name: "T-45a Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "T-51d Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "T-60a Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "T-60f Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "X-01 Mk I Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "Abraham's Relaxedwear", category: "Outfits", rarity: "Legendary" },
  { name: "Commander Uniform", category: "Outfits", rarity: "Legendary" },
  { name: "Confessor Cromwell's Rags", category: "Outfits", rarity: "Legendary" },
  { name: "Elder Robe", category: "Outfits", rarity: "Legendary" },
  { name: "Expert BoS Uniform", category: "Outfits", rarity: "Legendary" },
  { name: "Expert Flight Suit", category: "Outfits", rarity: "Legendary" },
  { name: "Expert Institute Jumper", category: "Outfits", rarity: "Legendary" },
  { name: "Expert Radiation Suit", category: "Outfits", rarity: "Legendary" },
  { name: "Expert Lab Coat", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy Combat Armor", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy Merc Gear", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy Raider Armor", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy nSynth Armor", category: "Outfits", rarity: "Legendary" },
  { name: "Heavy Wasteland Gear", category: "Outfits", rarity: "Legendary" },
  { name: "Lucky Formal Wear", category: "Outfits", rarity: "Legendary" },
  { name: "Scribe Rothchild's Robe", category: "Outfits", rarity: "Legendary" },
  { name: "T-51f Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "Three Dog's Outfit", category: "Outfits", rarity: "Legendary" },
  { name: "Wasteland Surgeon", category: "Outfits", rarity: "Legendary" },
  { name: "X-01 Mk VI Power Armor", category: "Outfits", rarity: "Legendary" },
  { name: "Rackie Jobinson's Jersey", category: "Outfits", rarity: "Legendary" },
  { name: "Minuteman Uniform", category: "Outfits", rarity: "Legendary" },
  { name: "Death's Jacket", category: "Outfits", rarity: "Legendary" },
  { name: "Rusty BB gun", category: "Weapons", rarity: "Common" },
  { name: "BB gun", category: "Weapons", rarity: "Common" },
  { name: "Rusty .32 Pistol", category: "Weapons", rarity: "Common" },
  { name: ".32 Pistol", category: "Weapons", rarity: "Common" },
  { name: "Enhanced BB Gun", category: "Weapons", rarity: "Common" },
  { name: "Enhanced .32 Pistol", category: "Weapons", rarity: "Common" },
  { name: "Pipe Pistol", category: "Weapons", rarity: "Common" },
  { name: "Rusty 10mm Pistol", category: "Weapons", rarity: "Common" },
  { name: "10mm Pistol", category: "Weapons", rarity: "Common" },
  { name: "Enhanced 10mm Pistol", category: "Weapons", rarity: "Common" },
  { name: "Rusty Scoped .44", category: "Weapons", rarity: "Common" },
  { name: "Hair Trigger Pipe Pistol", category: "Weapons", rarity: "Common" },
  { name: "Scoped .44", category: "Weapons", rarity: "Common" },
  { name: "Enhanced Scoped .44", category: "Weapons", rarity: "Common" },
  { name: "Rusty Lever-Action Rifle", category: "Weapons", rarity: "Common" },
  { name: "Lever-Action Rifle", category: "Weapons", rarity: "Common" },
  { name: "Enhanced Lever-Action Rifle", category: "Weapons", rarity: "Common" },
  { name: "Heavy Pipe Pistol", category: "Weapons", rarity: "Common" },
  { name: "Rusty Hunting Rifle", category: "Weapons", rarity: "Common" },
  { name: "Hunting Rifle", category: "Weapons", rarity: "Common" },
  { name: "Enhanced Hunting Rifle", category: "Weapons", rarity: "Common" },
  { name: "Pipe Rifle", category: "Weapons", rarity: "Common" },
  { name: "Rusty Sawed-Off Shotgun", category: "Weapons", rarity: "Common" },
  { name: "Sawed-Off Shotgun", category: "Weapons", rarity: "Common" },
  { name: "Enhanced Sawed-Off Shotgun", category: "Weapons", rarity: "Common" },
  { name: "Rusty Laser Pistol", category: "Weapons", rarity: "Common" },
  { name: "Hardened BB gun", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing BB Gun", category: "Weapons", rarity: "Rare" },
  { name: "Hardned .32 Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing .32 Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Hardned 10mm Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing 10mm Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Pool Cue", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Scoped .44", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing Scoped .44", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Lever-Action Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing Lever-Action Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Hunting Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Scoped Pipe Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing Hunting Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Kitchen Knife", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Saews-Off Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Laser Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Auto Pipe Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Double-Barrel Sawed-Off Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Assault Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Tuned Laser Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Assault Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Focused Laser Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Amplified Laser Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Assault Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Assault Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing Assault Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Baseball Bat", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Institute Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Snipper Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Night-Vision Pipe Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Sniper Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Double-Barrel Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Sniper Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Plasma Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Sniper Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Incendiary institute Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Plasma Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Armor Piercing Sniper Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Bayoneted Pipe Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Laser Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Tuned Plasma Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Focused Plasma Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Laser Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Butcher Knife", category: "Weapons", rarity: "Rare" },
  { name: "Improved institute Pistol", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Combat Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Tuned Laser Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Combat Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Focused Laser Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Combat Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Junk Jet", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Railway Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Combat Shotgun", category: "Weapons", rarity: "Rare" },
  { name: "Railway Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Railway Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Institute Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Flamer", category: "Weapons", rarity: "Rare" },
  { name: "Flamer", category: "Weapons", rarity: "Rare" },
  { name: "Recoil Compensated Junk Jet", category: "Weapons", rarity: "Rare" },
  { name: "Enhanced Flamer", category: "Weapons", rarity: "Rare" },
  { name: "Pickaxe", category: "Weapons", rarity: "Rare" },
  { name: "Risty Gauss Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Excited Institute Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Gauss Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Hardned Flamer", category: "Weapons", rarity: "Rare" },
  { name: "Pressurized Flamer", category: "Weapons", rarity: "Rare" },
  { name: "Rusty Plasma Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Tatical Junk Jet", category: "Weapons", rarity: "Rare" },
  { name: "Plasma Rifle", category: "Weapons", rarity: "Rare" },
  { name: "Lone Wanderer", category: "Weapons", rarity: "Legendary" },
  { name: "Blackhawk", category: "Weapons", rarity: "Legendary" },
  { name: "Lincoln's Repeater", category: "Weapons", rarity: "Legendary" },
  { name: "Little Brother", category: "Weapons", rarity: "Legendary" },
  { name: "Laser Musket", category: "Weapons", rarity: "Legendary" },
  { name: "Amplified Plasma Pistol", category: "Weapons", rarity: "Legendary" },
  { name: "Amplified Laser Rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Wazer Rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Accelerated Railway Rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Enhanced Gauss Rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Plasma Thrower", category: "Weapons", rarity: "Legendary" },
  { name: "Tuned Alien Blaster", category: "Weapons", rarity: "Legendary" },
  { name: "Amplified Plasma Rifle", category: "Weapons", rarity: "Legendary" },
  { name: "Focused Alien Blaster", category: "Weapons", rarity: "Legendary" },
  { name: "Amplified Alien Blaster", category: "Weapons", rarity: "Legendary" },
  { name: "Flaming Junk Jet", category: "Weapons", rarity: "Legendary" },
  { name: "Mean Green Monster", category: "Weapons", rarity: "Legendary" },
  { name: "Rusty Missile Launcher", category: "Weapons", rarity: "Legendary" },
  { name: "Armor Piercing Minigun", category: "Weapons", rarity: "Legendary" },
  { name: "Gatling Laser", category: "Weapons", rarity: "Legendary" },
  { name: "Guided Missile Launcher", category: "Weapons", rarity: "Legendary" },
  { name: "Relentless Raider Sword", category: "Weapons", rarity: "Legendary" },
  { name: "Fat Man", category: "Weapons", rarity: "Legendary" },
  { name: "Vengeance", category: "Weapons", rarity: "Legendary" },
  { name: "MIRV", category: "Weapons", rarity: "Legendary" },
  { name: "Dragon's Maw", category: "Weapons", rarity: "Legendary" }
]

items_list.each do |item_data|
  Item.create!(item_data)
end

puts "Criação de #{Item.count} itens concluída!"

