# db/seeds.rb

puts "Limpando a base de dados de itens..."
Item.destroy_all

puts "Criando itens..."

items_list = [
    { name: "Rusty Gauss Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Focused Gauss Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Gauss Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Gauss Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Tranq Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Tranq Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Tranq Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Tranq Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty T60 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "T60 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced T60 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened T60 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing T60 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "BOS Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced BOS Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened BOS Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing BOS Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Double-Barrel Combat Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Assaultron Head", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Assaultron Head", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Assaultron Head", "category": "Weapons", "rarity": "Rare" },
  { name: ".50 Cal Machine Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced .50 Cal Machine Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened .50 Cal Machine Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing .50 Cal Machine Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Calibrated Pipe Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Long Pipe Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Fire Hydrant Bat", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Power Fist", "category": "Weapons", "rarity": "Legendary" },
  { name: "Power Fist", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Power Fist", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Power Fist", "category": "Weapons", "rarity": "Legendary" },
  { name: "Ed's Custom Power Fist", "category": "Weapons", "rarity": "Legendary" },
  { name: "Grognak's Axe", "category": "Weapons", "rarity": "Legendary" },
  { name: "Wild Bill's Sidearm", "category": "Weapons", "rarity": "Legendary" },
  { name: "Infiltrator", "category": "Weapons", "rarity": "Legendary" },
  { name: "Red Rocket", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Gauss Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Accelerated Gauss Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Magnetron 4000", "category": "Weapons", "rarity": "Legendary" },
  { name: "Henrietta", "category": "Weapons", "rarity": "Legendary" },
  { name: "Ol' Painless", "category": "Weapons", "rarity": "Legendary" },
  { name: "Mare's Leg", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Railway Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Railmaster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Victory Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Charon's Shotgun", "category": "Weapons", "rarity": "Legendary" },
  { name: "Mountain Momma", "category": "Weapons", "rarity": "Legendary" },
  { name: "Kneecapper", "category": "Weapons", "rarity": "Legendary" },
  { name: "Farmer's Daughter", "category": "Weapons", "rarity": "Legendary" },
  { name: "Ghoul Revolver", "category": "Weapons", "rarity": "Legendary" },
  { name: "Alien Blaster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Destabilizer", "category": "Weapons", "rarity": "Legendary" },
  { name: "Firestarter", "category": "Weapons", "rarity": "Legendary"},
  { name: "Smuggler's End", "category": "Weapons", "rarity": "Legendary" },
  { name: "MPXL Novasurge", "category": "Weapons", "rarity": "Legendary" },
  { name: "Alien Disintegrator", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Alien Disintegrator", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Alien Disintegrator", "category": "Weapons", "rarity": "Legendary" },
  { name: "Tuned Plasma Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Focused Plasma Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Pulse Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Pulse Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Pulse Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Fat Man", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Fat Man", "category": "Weapons", "rarity": "Legendary" },
  { name: "Guided Fat Man", "category": "Weapons", "rarity": "Legendary" },
  { name: "Burnmaster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Tuned Gatling Laser", "category": "Weapons", "rarity": "Legendary" },
  { name: "Focused Gatling Laser", "category": "Weapons", "rarity": "Legendary" },
  { name: "Amplified Gatling Laser", "category": "Weapons", "rarity": "Legendary" },
  { name: "Minigun", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Minigun", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Minigun", "category": "Weapons", "rarity": "Legendary" },
  { name: "Lead Belcher", "category": "Weapons", "rarity": "Legendary" },
  { name: "Missile Launcher", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Missile Launcher", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Missile Launcher", "category": "Weapons", "rarity": "Legendary" },
  { name: "Plasma Caster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Plasma Caster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Hardened Plasma Caster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Plasma Caster", "category": "Weapons", "rarity": "Legendary"},
  { name: "Scoped Institute Pistol", "category": "Weapons", "rarity": "Legendary" },
  { name: "Scattered Institute Pistol", "category": "Weapons", "rarity": "Legendary" },
  { name: "Long Institute Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Night-Vision Institute Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Targeting Institute Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Virgil's Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Electrified Junk Jet", "category": "Weapons", "rarity": "Legendary" },
  { name: "Technician's Revenge", "category": "Weapons", "rarity": "Legendary" },
  { name: "Vengeance", "category": "Weapons", "rarity": "Legendary" },
  { name: "Big Sister", "category": "Weapons", "rarity": "Legendary" },
  { name: "Agitated Plasma Thrower", "category": "Weapons", "rarity": "Legendary" },
  { name: "Tactical Plasma Thrower", "category": "Weapons", "rarity": "Legendary" },
  { name: "Boosted Plasma Thrower", "category": "Weapons", "rarity": "Legendary" },
  { name: "Overcharged Plasma Thrower", "category": "Weapons", "rarity": "Legendary" },
  { name: "Vault Suit", "category": "Outfits", "rarity": "Common" },
  { name: "RobCo Factory Uniform", "category": "Outfits", "rarity": "Common" },
  { name: "Accountant Outfit", "category": "Outfits", "rarity": "Common" },
  { name: "Agent Provocateur", "category": "Outfits", "rarity": "Common" },
  { name: "Bespoke Attire", "category": "Outfits", "rarity": "Common" },
  { name: "BOS Casual", "category": "Outfits", "rarity": "Rare" },
  { name: "NCR Ranger Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "RobCo R&D Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Robot Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Bowling Shirt", "category": "Outfits", "rarity": "Rare" },
  { name: "Swing Dress", "category": "Outfits", "rarity": "Rare" },
  { name: "Elf Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Enclave Security Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Ghost Costume", "category": "Outfits", "rarity": "Rare" },
  { name: "Pilgrim Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Santa Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Skeleton Costume", "category": "Outfits", "rarity": "Rare" },
  { name: "Vault 33 Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Ma June Jacket", "category": "Outfits", "rarity": "Rare" },
  { name: "Sleazy Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Prewar Cowboy Costume", "category": "Outfits", "rarity": "Rare" },
  { name: "Wedding Dress", "category": "Outfits", "rarity": "Rare" },
  { name: "Action Wedding Dress", "category": "Outfits", "rarity": "Rare" },
  { name: "Vault Security Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Heavy Vault Suit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Battle Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Expert Jumpsuit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Exterminator", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Leather Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Commander Fatigues", "category": "Outfits", "rarity": "Legendary" },
  { name: "Lucky Nightwear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Mutant Hunter Gear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Metal Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Tattered Longcoat", "category": "Outfits", "rarity": "Legendary" },
  { name: "Autumn's Uniform", "category": "Outfits", "rarity": "Legendary" },
  { name: "Bittercup's Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Eulogy Jones' Suit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Incognito Leisurewear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Lucy's Vault Suit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Moldaver's Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Nuka-Girl Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Overseer's Office Wear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Piper's Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Preston's Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Rachel's Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Sarah Lyons' Brotherhood Fatigues", "category": "Outfits", "rarity": "Legendary" },
  { name: "Silver Shroud Costume", "category": "Outfits", "rarity": "Legendary" },
  { name: "Virgil's Lab Coat", "category": "Outfits", "rarity": "Legendary" },
  { name: "Wasteland Wanderer", "category": "Outfits", "rarity": "Legendary" },
  { name: "Zeta Alien Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Zeta Alien Spacesuit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Tunnel Snake Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Mechanist Jumpsuit", "category": "Outfits", "rarity": "Common" },
  { name: "Polka Dot Sundress", "category": "Outfits", "rarity": "Common" },
  { name: "Pre-War Suburbanite", "category": "Outfits", "rarity": "Common" },
  { name: "Rural Schoolmarm", "category": "Outfits", "rarity": "Common" },
  { name: "Spring Casualwear", "category": "Outfits", "rarity": "Common" },
  { name: "Vault Socialite", "category": "Outfits", "rarity": "Common" },
  { name: "Armored Vault Suit", "category": "Outfits", "rarity": "Common" },
  { name: "Battle Armor", "category": "Outfits", "rarity": "Common" },
  { name: "BoS Uniform", "category": "Outfits", "rarity": "Common" },
  { name: "Combat Armor", "category": "Outfits", "rarity": "Common" },
  { name: "Flight Suit", "category": "Outfits", "rarity": "Common" },
  { name: "Formal Wear", "category": "Outfits", "rarity": "Common" },
  { name: "Handyman Jumpsuit", "category": "Outfits", "rarity": "Common" },
  { name: "Initiate Robe", "category": "Outfits", "rarity": "Common" },
  { name: "Junior Officer Uniform", "category": "Outfits", "rarity": "Common" },
  { name: "Lab Coat", "category": "Outfits", "rarity": "Common" },
  { name: "Leather Armor", "category": "Outfits", "rarity": "Common" },
  { name: "Merc Gear", "category": "Outfits", "rarity": "Common" },
  { name: "Military Fatigues", "category": "Outfits", "rarity": "Common" },
  { name: "Nightwear", "category": "Outfits", "rarity": "Common" },
  { name: "Radiation Suit", "category": "Outfits", "rarity": "Common" },
  { name: "Raider Armor", "category": "Outfits", "rarity": "Common" },
  { name: "Treasure Gear", "category": "Outfits", "rarity": "Common" },
  { name: "Wasteland Gear", "category": "Outfits", "rarity": "Common" },
  { name: "Wasteland Medic", "category": "Outfits", "rarity": "Common" },
  { name: "Business Suit", "category": "Outfits", "rarity": "Common" },
  { name: "Country Girl", "category": "Outfits", "rarity": "Common" },
  { name: "Waitress Uniform", "category": "Outfits", "rarity": "Common" },
  { name: "Doo-Wop Singer", "category": "Outfits", "rarity": "Common" },
  { name: "Drag Racer", "category": "Outfits", "rarity": "Common" },
  { name: "Post-War Casanova", "category": "Outfits", "rarity": "Common" },
  { name: "Soda Fountain Dress", "category": "Outfits", "rarity": "Common" },
  { name: "Advanced BoS Uniform", "category": "Outfits", "rarity": "Rare" },
  { name: "Advanced Flight Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Advanced Institute Jumper", "category": "Outfits", "rarity": "Rare" },
  { name: "Advanced Jumpsuit", "category": "Outfits", "rarity": "Rare" },
  { name: "Advanced Lab Coat", "category": "Outfits", "rarity": "Rare" },
  { name: "Advanced Radiation Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Baseball Uniform", "category": "Outfits", "rarity": "Rare" },
  { name: "Bounty Hunter Gear", "category": "Outfits", "rarity": "Rare" },
  { name: "Clergy Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Comedian Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Engineer Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Fancy Formal Wear", "category": "Outfits", "rarity": "Rare" },
  { name: "Greaser Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Horror Fan Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Knight Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Librarian Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Lifeguard Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Mayor Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Medieval Ruler Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Movie Fan Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Naughty Nightwear", "category": "Outfits", "rarity": "Rare" },
  { name: "Ninja Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Nobility Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Officer Fatigues", "category": "Outfits", "rarity": "Rare" },
  { name: "Officer Uniform", "category": "Outfits", "rarity": "Rare" },
  { name: "Professor Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Republic Robes", "category": "Outfits", "rarity": "Rare" },
  { name: "Sci-Fi Fan Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Scribe Robe", "category": "Outfits", "rarity": "Rare" },
  { name: "Soldier Uniform", "category": "Outfits", "rarity": "Rare" },
  { name: "Sports Fan Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Battle Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Combat Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Leather Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Merc Gear", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Metal Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Raider Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Vault Suit", "category": "Outfits", "rarity": "Rare" },
  { name: "Sturdy Wasteland Gear", "category": "Outfits", "rarity": "Rare" },
  { name: "Surgeon Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Survivor Armor", "category": "Outfits", "rarity": "Rare" },
  { name: "Swimsuit", "category": "Outfits", "rarity": "Rare" },
  { name: "Wasteland Doctor", "category": "Outfits", "rarity": "Rare" },
  { name: "Wrestler Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "Motorcycle Jacket", "category": "Outfits", "rarity": "Rare" },
  { name: "T-45a Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "T-51d Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "T-60a Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "T-60f Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "X-01 Mk I Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Abraham's Relaxedwear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Commander Uniform", "category": "Outfits", "rarity": "Legendary" },
  { name: "Confessor Cromwell's Rags", "category": "Outfits", "rarity": "Legendary" },
  { name: "Elder Robe", "category": "Outfits", "rarity": "Legendary" },
  { name: "Expert BoS Uniform", "category": "Outfits", "rarity": "Legendary" },
  { name: "Expert Flight Suit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Expert Institute Jumper", "category": "Outfits", "rarity": "Legendary" },
  { name: "Expert Radiation Suit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Expert Lab Coat", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Combat Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Merc Gear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Raider Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Synth Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Wasteland Gear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Lucky Formal Wear", "category": "Outfits", "rarity": "Legendary" },
  { name: "Scribe Rothchild's Robe", "category": "Outfits", "rarity": "Legendary" },
  { name: "T-51f Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Three Dog's Outfit", "category": "Outfits", "rarity": "Legendary" },
  { name: "Wasteland Surgeon", "category": "Outfits", "rarity": "Legendary" },
  { name: "X-01 Mk VI Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "X-01 Mk IV Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Rackie Jobinson's Jersey", "category": "Outfits", "rarity": "Legendary" },
  { name: "Minuteman Uniform", "category": "Outfits", "rarity": "Legendary" },
  { name: "Death's Jacket", "category": "Outfits", "rarity": "Legendary" },
  { name: "Rusty BB Gun", "category": "Weapons", "rarity": "Common" },
  { name: "BB Gun", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty .32 Pistol", "category": "Weapons", "rarity": "Common" },
  { name: ".32 Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced BB Gun", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced .32 Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Pipe Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty 10mm Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "10mm Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced 10mm Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty Scoped .44", "category": "Weapons", "rarity": "Common" },
  { name: "Hair Trigger Pipe Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Scoped .44", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced Scoped .44", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty Lever-Action Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Lever-Action Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced Lever-Action Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Heavy Pipe Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty Hunting Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Hunting Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced Hunting Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Pipe Rifle", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty Sawed-Off Shotgun", "category": "Weapons", "rarity": "Common" },
  { name: "Sawed-Off Shotgun", "category": "Weapons", "rarity": "Common" },
  { name: "Enhanced Sawed-Off Shotgun", "category": "Weapons", "rarity": "Common" },
  { name: "Rusty Laser Pistol", "category": "Weapons", "rarity": "Common" },
  { name: "Hardened BB Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing BB Gun", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened .32 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing .32 Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened 10mm Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing 10mm Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Pool Cue", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Scoped .44", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing Scoped .44", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Lever-Action Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing Lever-Action Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Hunting Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Scoped Pipe Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing Hunting Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Kitchen Knife", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Sawed-Off Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Laser Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Auto Pipe Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Double-Barrel Sawed-Off Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Tuned Laser Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Focused Laser Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Amplified Laser Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing Assault Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Baseball Bat", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Institute Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Snipper Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Night-Vision Pipe Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Sniper Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Double-Barrel Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Sniper Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Plasma Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Sniper Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Incendiary institute Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Plasma Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Armor Piercing Sniper Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Bayoneted Pipe Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Laser Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Tuned Plasma Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Focused Plasma Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Laser Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Butcher Knife", "category": "Weapons", "rarity": "Rare" },
  { name: "Improved institute Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Combat Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Tuned Laser Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Combat Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Focused Laser Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Combat Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Junk Jet", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Railway Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Combat Shotgun", "category": "Weapons", "rarity": "Rare" },
  { name: "Railway Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Railway Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Institute Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Flamer", "category": "Weapons", "rarity": "Rare" },
  { name: "Flamer", "category": "Weapons", "rarity": "Rare" },
  { name: "Recoil Compensated Junk Jet", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Flamer", "category": "Weapons", "rarity": "Rare" },
  { name: "Pickaxe", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Gauss Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Excited Institute Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Gauss Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Flamer", "category": "Weapons", "rarity": "Rare" },
  { name: "Pressurized Flamer", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Plasma Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Tatical Junk Jet", "category": "Weapons", "rarity": "Rare" },
  { name: "Plasma Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Lone Wanderer", "category": "Weapons", "rarity": "Legendary" },
  { name: "Blackhawk", "category": "Weapons", "rarity": "Legendary" },
  { name: "Lincoln's Repeater", "category": "Weapons", "rarity": "Legendary" },
  { name: "Little Brother", "category": "Weapons", "rarity": "Legendary" },
  { name: "Laser Musket", "category": "Weapons", "rarity": "Legendary" },
  { name: "Amplified Plasma Pistol", "category": "Weapons", "rarity": "Legendary" },
  { name: "Amplified Laser Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Wazer Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Accelerated Railway Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Enhanced Gauss Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Plasma Thrower", "category": "Weapons", "rarity": "Legendary" },
  { name: "Tuned Alien Blaster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Amplified Plasma Rifle", "category": "Weapons", "rarity": "Legendary" },
  { name: "Focused Alien Blaster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Amplified Alien Blaster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Scoped Alien Blaster", "category": "Weapons", "rarity": "Legendary"},
  { name: "Long Alien Blaster", "category": "Weapons", "rarity": "Legendary"},
  { name: "Capacitor Alien Blaster", "category": "Weapons", "rarity": "Legendary"},
  { name: "Brutal Alien Blaster", "category": "Weapons", "rarity": "Legendary"},
  { name: "Flaming Junk Jet", "category": "Weapons", "rarity": "Legendary" },
  { name: "Mean Green Monster", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Missile Launcher", "category": "Weapons", "rarity": "Legendary" },
  { name: "Armor Piercing Minigun", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Minigun", "category": "Weapons", "rarity": "Legendary"},
  { name: "Gatling Laser", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Gatling Laser", "category": "Weapons", "rarity": "Legendary"},
  { name: "Guided Missile Launcher", "category": "Weapons", "rarity": "Legendary" },
  { name: "Relentless Raider Sword", "category": "Weapons", "rarity": "Legendary" },
  { name: "Fat Man", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Fat Man", "category": "Weapons", "rarity": "Legendary" },
  { name: "Vengeance", "category": "Weapons", "rarity": "Legendary" },
  { name: "MIRV", "category": "Weapons", "rarity": "Legendary" },
  { name: "Dragon's Maw", "category": "Weapons", "rarity": "Legendary" },
  { name: "Rusty Junk Jet", "category": "Weapons", "rarity": "Common" },
  { name: "Combat Knife", "category": "Weapons", "rarity": "Rare" },
  { name: "Tire Iron", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Laser Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Laser Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Scoped Laser Musket", "category": "Weapons", "rarity": "Rare" },
  { name: "Long Laser Musket", "category": "Weapons", "rarity": "Rare" },
  { name: "Capacitor Laser Musket", "category": "Weapons", "rarity": "Rare" },
  { name: "Brutal Laser Musket", "category": "Weapons", "rarity": "Rare" },
  { name: "Scattered Laser Musket", "category": "Weapons", "rarity": "Legendary"},
  { name: "Boosted Laser Musket", "category": "Weapons", "rarity": "Legendary"},
  { name: "Enhanced Laser Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Laser Rifle", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Plasma Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Plasma Pistol", "category": "Weapons", "rarity": "Rare" },
  { name: "Magnetron 2000", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Junk Jet", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Junk Jet", "category": "Weapons", "rarity": "Rare" },
  { name: "Ignition Junk Jet", "category": "Weapons", "rarity": "Rare" },
  { name: "Rusty Ripper", "category": "Weapons", "rarity": "Rare" },
  { name: "Ripper", "category": "Weapons", "rarity": "Rare" },
  { name: "Enhanced Ripper", "category": "Weapons", "rarity": "Rare" },
  { name: "Hardened Ripper", "category": "Weapons", "rarity": "Rare" },
  { name: "Metal Armor", "category": "Outfits", "rarity": "Common" },
  { name: "Institute Jumper", "category": "Outfits", "rarity": "Common" },
  { name: "Detective Outfit", "category": "Outfits", "rarity": "Rare" },
  { name: "T-45d Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "T-45f Power Armor", "category": "Outfits", "rarity": "Legendary"},
  { name: "T-51a Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "X-01 Mk V Power Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Synth Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Heavy Synth Armor", "category": "Outfits", "rarity": "Legendary"},
  { name: "War's Armor", "category": "Outfits", "rarity": "Legendary" },
  { name: "Famine's Vestment", "category": "Outfits", "rarity": "Legendary" },
  { name: "Pestilence's Plating", "category": "Outfits", "rarity": "Legendary" },
  { name: "Death's Coat", "category": "Outfits", "rarity": "Legendary" },
  { name: "All-American", "category": "Outfits", "rarity": "Legendary" },
  { name: "Oktoberfest Garb", "category": "Outfits", "rarity": "Legendary" },
  { name: "Leprechaun Suit", "category": "Outfits", "rarity": "Legendary" }
]

items_list.each do |item_data|
  Item.create!(item_data)
end

puts "Criação de #{Item.count} itens concluída!"
